language: node_js
node_js:
  - "10"

# Build on Ubuntu Xenial (16.04)
dist: xenial
sudo: required

services:
  - docker

# https://github.com/greenkeeperio/greenkeeper-lockfile/issues/156
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

script: "npm run test"

before_install:
  - npm install -g mkdirp

# Send coverage data to Coveralls
#after_success:
#  - npm run coverage

# Deploy with semantic release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
